spring.application.name=market-dashboard-backend
##Properties Application
token_finnhub=d740j8pr01qno4pvvp1gd740j8pr01qno4pvvp20
token_alpha_vantage=T7II0JTMT667032W
base_url_finnhub=https://finnhub.io/api/v1/
base_url_alpha_vantage=https://www.alphavantage.co/query?